#!/usr/bin/env bash
# SessionStart hook — snapshot the user-scope MCP servers from ~/.claude.json
# into the dotfiles source as a redacted reference, so config drift shows up
# as a git diff. Must never fail the session (always exit 0).
set -uo pipefail

SRC="$HOME/.claude.json"
OUT="$HOME/dev/dotfiles/dot_claude/mcp-servers.reference.json"

command -v jq >/dev/null 2>&1 || exit 0
[ -f "$SRC" ] || exit 0
[ -d "$(dirname "$OUT")" ] || exit 0

COMMENT="Redacted reference snapshot of the user-scope mcpServers in ~/.claude.json, auto-regenerated by the mcp-snapshot SessionStart hook for drift tracking. Sensitive values (tokens/keys/auth) are REDACTED. Not loaded by Claude Code; documentation only. A git diff here means a user-scope MCP server changed."

SNAPSHOT=$(jq --arg comment "$COMMENT" '
  def scrub:
    walk(
      if type == "object" then
        with_entries(
          if (.key | ascii_downcase
                   | test("token|secret|password|api[_-]?key|authorization|bearer|credential"))
          then .value = "REDACTED"
          else . end
        )
      else . end
    );
  { _comment: $comment, mcpServers: ((.mcpServers // {}) | scrub) }
' "$SRC" 2>/dev/null) || exit 0

# Only rewrite when content actually changed, to keep diffs meaningful.
if [ ! -f "$OUT" ] || [ "$SNAPSHOT" != "$(cat "$OUT" 2>/dev/null)" ]; then
  printf '%s\n' "$SNAPSHOT" > "$OUT" 2>/dev/null || exit 0
fi

exit 0
